spring.application.name=learning-jpa

spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update

spring.h2.console.enabled=true

# Hi?n SQL
spring.jpa.show-sql=true

# SQL format ??p h?n
spring.jpa.properties.hibernate.format_sql=false

# N?u mu?n in luôn giá tr? bind parameter
spring.jpa.properties.hibernate.type=trace
